return {
	groundlightning = {
		areaofeffect = 12,
		avoidfeature = false,
		beamtime = 0.12,
		corethickness = 0.175,
		craterareaofeffect = 0,
		craterboost = 0,
		cratermult = 0,
		energypershot = 20,
		explosiongenerator = "custom:WORMSIGN_LIGHTNING_SMALL",
		firestarter = 30,
		impactonly = 1,
		impulseboost = 0,
		impulsefactor = 0,
		laserflaresize = 10,
		name = "GroundLightning",
		noselfdamage = true,
		range = 430,
		reloadtime = 0.48,
		rgbcolor = "1 0 0",
		soundstart = "Spark1",
		targetmoveerror = 0.1,
		thickness = 2.5,
		tolerance = 10000,
		turret = true,
		weapontype = "BeamLaser",
		weaponvelocity = 2250,
		damage = {
			default = 0,
		},
	},
}