return {
	wormlightning = {
		areaofeffect = 1,
		avoidfeature = false,
		minintensity = 1.0,
		intensity = 1.0,
		beamtime = 1,
		beamttl = 30,
		corethickness = 1.0,
		energypershot = 1,
		firestarter = 30,
		laserflaresize = 3,
		name = "WormLightning",
		range = 49,
		reloadtime = 1.0,
		rgbcolor = "1 0 1",
		rgbcolor2 = "1 0 1",
		thickness = 3.0,
		tolerance = 10000,
		weaponvelocity = 500,
		weapontype = "BeamLaser",
		damage = {
			default = 100,
		},
	},
	wormlightningbad = {
		areaofeffect = 12,
		avoidfeature = false,
		beamtime = 0.12,
		corethickness = 0.175,
		craterareaofeffect = 0,
		craterboost = 0,
		cratermult = 0,
		energypershot = 20,
		explosiongenerator = "custom:SMALL_RED_BURN",
		firestarter = 30,
		impactonly = 1,
		impulseboost = 0,
		impulsefactor = 0,
		laserflaresize = 10,
		name = "WormLightningBad",
		noselfdamage = true,
		range = 430,
		reloadtime = 0.48,
		rgbcolor = "1 0 1",
		soundhitdry = "",
		soundhitwet = "sizzle",
		soundhitwetvolume = 0.5,
		soundstart = "lasrfir3",
		soundtrigger = 1,
		targetmoveerror = 0.1,
		thickness = 2.5,
		tolerance = 10000,
		turret = true,
		weapontype = "BeamLaser",
		weaponvelocity = 2250,
		damage = {
			bombers = 5,
			commanders = 140,
			default = 75,
			fighters = 5,
			subs = 3,
			vtol = 5,
		},
	},
}