return {
	sworm = {
		blocking = true,
		buildPic = "sworm.png",
		canMove = true,
		description = "Giant hungry beast.",
		footprintX = 6,
		footprintZ = 6,
		iconType = "sworm",
		levelGround = false,
		maxDamage = 9999,
		name = "Sand Worm",
		objectName = "swormOpenMouth-180_50out-r45.s3o",
		script = [[sWormOpenMouth.lua]],
		stealth = true,
 		-- collisionVolumeType = "cylY",
 		usePieceCollisionVolumes = true,
		-- isTransport = true,
		-- loadingRadius = 256,
		-- isFirePlatform = true,
		-- transmaxunits = [[10]],
		-- transportCapacity = 1000,
  		-- transportMass = 500000,
 		-- transportSize = 100000,
		customParams = {
 			ignoreplacementrestriction = true,
		},
	},
	underworm = {
		blocking = false,
		buildPic = "sworm.png",
		canMove = true,
		description = "I'd like to be under the sand in a sand worm's garden.",
		footprintX = 1,
		footprintZ = 1,
		iconType = "sworm",
		levelGround = false,
		maxDamage = 9999,
		name = "Sand Worm Underground",
		objectName = "swormOpenMouth-180_50out-r45.s3o",
		script = [[nullscript.lua]],
		canFly = true,
		cruiseAlt = 160,
		-- stealth = false,
		-- canCloak = true,
		-- startCloaked = true,
		-- initCloaked = true,
		-- decloakOnFire = false,
		customParams = {
 			ignoreplacementrestriction = true,
		},
	},
}
