return {
	sworm = {
		blocking = true,
		buildPic = "sworm.png",
		canMove = true,
		description = "Giant hungry beast.",
		footprintX = 6,
		footprintZ = 6,
		iconType = "sworm",
		levelGround = false,
		maxDamage = 9999,
		name = "Sand Worm",
		objectName = "swormTrilipClosedMouth-20below.s3o",
		script = [[sWormTrilipClosedMouth.lua]],
		stealth = true,
 		usePieceCollisionVolumes = true,
		customParams = {
 			ignoreplacementrestriction = true,
		},
	},
	sworm1 = {
		blocking = true,
		buildPic = "sworm.png",
		canMove = true,
		description = "Giant hungry beast.",
		footprintX = 6,
		footprintZ = 6,
		iconType = "sworm",
		levelGround = false,
		maxDamage = 9999,
		name = "Sand Worm",
		objectName = "swormTrilipClosedMouth-20below.s3o",
		script = [[sWormTrilipClosedMouthScaling.lua]],
		stealth = true,
 		usePieceCollisionVolumes = true,
		customParams = {
 			ignoreplacementrestriction = true,
		},
	},
	sworm2 = {
		blocking = true,
		buildPic = "sworm.png",
		canMove = true,
		description = "Giant hungry beast.",
		footprintX = 12,
		footprintZ = 12,
		iconType = "sworm",
		levelGround = false,
		maxDamage = 9999,
		name = "Sand Worm",
		objectName = "swormTrilipClosedMouth-20below-scale2x.s3o",
		script = [[sWormTrilipClosedMouthScaling.lua]],
		stealth = true,
 		usePieceCollisionVolumes = true,
		customParams = {
 			ignoreplacementrestriction = true,
		},
	},
	sworm3 = {
		blocking = true,
		buildPic = "sworm.png",
		canMove = true,
		description = "Giant hungry beast.",
		footprintX = 18,
		footprintZ = 18,
		iconType = "sworm",
		levelGround = false,
		maxDamage = 9999,
		name = "Sand Worm",
		objectName = "swormTrilipClosedMouth-20below-scale3x.s3o",
		script = [[sWormTrilipClosedMouthScaling.lua]],
		stealth = true,
 		usePieceCollisionVolumes = true,
		customParams = {
 			ignoreplacementrestriction = true,
		},
	},
	underworm = {
		blocking = false,
		buildPic = "sworm.png",
		canMove = true,
		description = "I'd like to be under the sand in a sand worm's garden.",
		footprintX = 1,
		footprintZ = 1,
		iconType = "sworm",
		levelGround = false,
		maxDamage = 9999,
		name = "Sand Worm Underground",
		objectName = "swormOpenMouth-180_50out-r45.s3o",
		script = [[nullscript.lua]],
		canFly = true,
		cruiseAlt = 160,
		-- stealth = false,
		-- canCloak = true,
		-- startCloaked = true,
		-- initCloaked = true,
		-- decloakOnFire = false,
		customParams = {
 			ignoreplacementrestriction = true,
		},
	},
}
